[programs.devnet]
project_registry = "DZBcioGMWiriWXejSRYo3kjVJtS9VLe5RvwdUhr5HxJN"
compliance_transfer = "BYg6sLi3UHLPB8de7J6Z3wAM5PcdV9T5HxtqBfuD85V9"
allocation_distribution = "EZXJQXX2vYoDrUP6JUcqeShhqKpSRuDecLK9JUiVzkTz"

[provider]
cluster = "devnet"


[scripts]
test = "mocha -t 1000000 tests/**/*.ts"
