export default {
  designSystem: {
    color: {
      black: '#000',
      white: '#fff',
    },
    gradient: {},
    theme: {
      document: {
        '@light': {
          color: 'black',
          background: 'white',
        },
        '@dark': {
          color: 'white',
          background: 'black',
        },
      },
      none: {
        color: 'none',
        background: 'none',
      },
      transparent: {
        color: 'currentColor',
        background: 'transparent',
      },
    },
    font: {},
    font_family: {},
    typography: {
      base: 16,
      ratio: 1.25,
      subSequence: true,
      templates: {},
    },
    spacing: {
      base: 16,
      ratio: 1.618,
      subSequence: true,
    },
    timing: {},
    class: {},
    grid: {},
    icons: {},
    shape: {},
    reset: {},
    animation: {},
    media: {},
  },
  components: {},
  integrations: {},
  snippets: {},
  pages: {},
  state: {},
  files: {},
  dependencies: {},
  methods: {},
  functions: {},
  secrets: {},
  fetch: {},
  router: {},
  useReset: true,
  useVariable: true,
  useFontImport: true,
  useIconSprite: true,
  useSvgSprite: true,
  useDefaultConfig: true,
  useDocumentTheme: true,
  verbose: false,
  globalTheme: 'auto',
};