use anchor_lang::prelude::*;
use crate::state::SubscriptionStatus;

/// Per-investor subscription – PDA seeds: [b"subscription", investor_pubkey, subscription_id]
#[account]
pub struct InvestmentSubscriptionAccount {
    /// Unique ID for this subscription session (generated by backend/cli)
    pub subscription_id:        u64,                //  8
    /// The investor wallet
    pub investor:               Pubkey,             // 32
    /// target project from Program 1
    pub project_id:             u64,                //  8
    /// Amount invested in payment asset decimals
    pub investment_amount:      u64,                //  8
    /// USDC or USDT mint address
    pub payment_asset:          Pubkey,             // 32
    /// Pending -> Settled -> Allocated
    pub status:                 SubscriptionStatus, //  1
    /// Reference to off-chain payment (USDC transfer tx hash)
    pub settlement_tx_hash:     [u8; 64],           // 64
    /// How many tokens will be/were issued
    pub allocated_token_amount: u64,                //  8
    pub created_at:             i64,                //  8
    pub settled_at:             i64,                //  8
    pub bump:                   u8,                 //  1
}

impl InvestmentSubscriptionAccount {
    // 8 (disc) + 8 + 32 + 8 + 8 + 32 + 1 + 64 + 8 + 8 + 8 + 1 + 32 (padding) = 218
    pub const SIZE: usize = 8 + 8 + 32 + 8 + 8 + 32 + 1 + 64 + 8 + 8 + 8 + 1 + 32;
}
